language: node_js
node_js:
  - "8"

before_install:
  - yarn add codecov

script:
  - yarn install
  - yarn lint
  - yarn test

after_success:
 - codecov

cache:
  yarn: true
  directories:
    - node_modules