FROM node:8
MAINTAINER eq.team@ons.gov.uk

ARG APPLICATION_VERSION
ENV EQ_PUBLISHER_VERSION $APPLICATION_VERSION

EXPOSE 9000
WORKDIR /app

ENTRYPOINT yarn start

# Install
COPY . /app
RUN yarn install