{
    questionnaire(id: $questionnaireId) {
        id
        title
        description
        theme
        legalBasis
        navigation
        pages {
          id
          title
          description
          questions {
            id
            title
            description
            guidance
            type
            mandatory
            createdAt
            updatedAt
            answers {
              id
              description
              guidance
              qCode
              label
              type
              mandatory
              createdAt
              updatedAt
            }
          }
        }
	}
}